services:
  git-proxy:
    build: .
    container_name: git-v2-proxy
    ports:
      - "7080:80"
    environment:
      - AZURE_DEVOPS_URL
      - AZURE_PAT
      - REPO_NAME
      - SYNC_INTERVAL
    volumes:
      - git-repos:/repos
    restart: unless-stopped

volumes:
  git-repos:
